name: update_table

on:
  schedule:
    - cron: '0 15 * * *'  # 毎日 00:00 JST（UTC 15:00）
    - cron: '0 1 * * 3'   # 毎週水曜 10:00 JST（UTC 01:00）
  workflow_dispatch:
    inputs:
      target:
        description: 'daily か weekly を選択'
        required: false
        default: 'daily'
        type: choice
        options: [daily, weekly]

env:
  GOOGLE_SHEET_KEY: ${{ secrets.GOOGLE_SHEET_KEY }}

jobs:
  daily:
    # schedule(毎日0時JST) or push or 手動(daily) のとき実行
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 15 * * *') ||
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'daily')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: update-table-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: dist

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread gspread-formatting dotenv google-api-python-client beautifulsoup4 aiohttp

      - name: Run daily script
        run: |
          cp -rf ./public/* ./dist
          python ./src/daily.py

      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  weekly:
    # schedule(毎週水曜10時JST) or 手動(weekly) のとき実行
    if: |
      (github.event_name == 'schedule' && github.event.schedule == '0 1 * * 3') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'weekly')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    concurrency:
      group: update-table-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: dist

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread gspread-formatting ßdotenv google-api-python-client beautifulsoup4 aiohttp

      - name: Run weekly script
        run: |
          cp -rf ./public/* ./dist
          python ./src/weekly.py

      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
